# Generated by Django 4.2.6 on 2023-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('one_bed', models.IntegerField()),
                ('name', models.CharField(max_length=55)),
                ('two_bed', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('is_prepayment', models.BooleanField(default=False)),
                ('min_prepayment', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='House_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('admin_comment', models.CharField(blank=True, null=True)),
                ('total_coast', models.FloatField()),
                ('prepayment', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
    ]
